name: Upload Database

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: containerbase/internal-tools/setup@a9188b7980bb1d8d9fe8647bd07e925f8e017edd # v4.5.10
        with:
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm start
        env:
          GITHUB_TOKEN: ${{ github.token }}
