name: Upload Database

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: containerbase/internal-tools/setup@5178443c240fc03a38e95c6fc7283938f4b3f4f4 # v4.6.27
        with:
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm start
        env:
          GITHUB_TOKEN: ${{ github.token }}
