name: Upload Database

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: containerbase/internal-tools/setup@50645dd090d12fb3fbbcf4dba02f558d93599856 # v4.2.5
        with:
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm start
        env:
          GITHUB_TOKEN: ${{ github.token }}
